### ISSUE TITLE
Crashes on startup on 1.19 (Quilt loader)

### ISSUE THREAD

**Issue by ghost** [Tschipcraft/fabric_make_bubbles_pop_mod#1]
title

**Comment by Tschipcraft** [comment]
The new release [0.0.2](https://github.com/Tschipcraft/fabric_make_bubbles_pop_mod/releases/tag/0.0.2) should work for Minecraft 1.19. I personally can't test for quilt loader compatibility at the moment

**Comment by ghost** [comment]
Works perfectly fine with quilt!
