### ISSUE TITLE
Minecraft 1.18.2 crashes after TNT or creeper exploded in water or flowing water with this mod

### ISSUE THREAD

**Issue by 02second** [Tschipcraft/fabric_make_bubbles_pop_mod#10]
### Describe the bug

Prime the TNT or creeper and make it explode in the water or flowing water, then the game will crash. I found this would happen in Minecraft 1.18.2 with the 0.2.0 version of the mod, but it didn't happen in Minecraft 1.20.4. And it's in Fabric.

### Steps to reproduce

1. Minecraft 1.18.2, Fabric 0.15.6 and Fabric API 0.77.0+1.18.2
2. Prime the TNT or creeper in the water or summon TNT using command
3. Wait until it explodes

### Expected behavior

The game will crash and a crash report will generate.

### Additional context

The crash report is here.[crash-2024-02-06_17.46.35-client.txt](https://github.com/Tschipcraft/make_bubbles_pop/files/14178406/crash-2024-02-06_17.46.35-client.txt)

**Comment by Tschipcraft** [comment]
Thank you for the bug report. This must have slipped through when I was testing the 1.18 version.

**Comment by Tschipcraft** [comment]
A fix for this issue is now online on all platforms.

**Comment by 02second** [comment]
The problem is fixed. Great!👍
