### ISSUE TITLE
Nitpick: Literal newline in `fabric.mod.json` of 0.2.0 artifact

### ISSUE THREAD

**Issue by YoshiRulz** [Tschipcraft/fabric_make_bubbles_pop_mod#12]
This doesn't seem to be a problem for the Fabric loader, but a strict parser like `jq`'s will choke on literal newlines in strings.
Since it's not literal in the source:
https://github.com/Tschipcraft/make_bubbles_pop/blob/f23c11c4fcf519320bebc35fc4d2538122b73361/fabric/src/main/resources/fabric.mod.json#L6
...I'm guessing the process of expanding templates is what introduces it.

**Comment by Tschipcraft** [comment]
Interesting, I did not know that happens. I'm pretty much just using the default build config from fabric's example mod, so I'm not sure how I could fix this permanently (sure I could just overwrite the fabric.mod.json when it's built, but I kinda don't want to do that every time). If you have any suggestions (except removing the newline lol), feel free to let me know

**Comment by YoshiRulz** [comment]
I found 2 mods which don't have the same problem, and they both have this in their build scripts:
```groovy
expand(stringProperties) {
	escapeBackslash = true
}
```
- [in Chat Heads](https://github.com/dzwdz/chat_heads/blob/ce139df40ed9f4b33e116898dd76b31c7df02ded/build.gradle#L63)
- [in Falling Leaves](https://github.com/RandomMcSomethin/fallingleaves/blob/692f86426f90be91794724757c200871cdc4ba68/build.gradle#L50)

**Comment by Tschipcraft** [comment]
Thank you for the observation, I will try this out

**Comment by Tschipcraft** [comment]
The extra line fixed this issue. All builds moving forwards will not have literal new lines in their `fabric.mod.json` 🎉

**Comment by YoshiRulz** [comment]
Thank you! I'll try and get that fixed in the Fabric mod template too.
