### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Pie-Not-Lie** [Tschipcraft/fabric_make_bubbles_pop_mod#15]
### Is your feature request related to a problem? Please describe.

No.

### Describe the feature you'd like

Mod needs updated to the latest version.

### Describe alternatives you've considered

N/A

### Additional context

Love the mod. Thanks!

**Comment by Tschipcraft** [comment]
I will finalize v0.3.0 with 1.21 support in approx. 2 weeks after my finals. Thanks for your patience!

**Comment by Pie-Not-Lie** [comment]
Of course! Take your time and best of luck on finals! :D
