### ISSUE TITLE
Bubbles not Appearing

### ISSUE THREAD

**Issue by Bkxz** [Tschipcraft/fabric_make_bubbles_pop_mod#2]
### Describe the bug

Bubbles that are underwater will not appear if I am not underwater. Same applies to the opposite (Bubbles above water not appearing if I am underwater)

<img width="1440" alt="Screenshot 2023-05-20 at 19 01 39" src="https://github.com/Tschipcraft/fabric_make_bubbles_pop_mod/assets/101755807/e3c5a5a1-14e9-4d1e-9187-323e82ee457b">
<img width="1440" alt="Screenshot 2023-05-20 at 19 01 47" src="https://github.com/Tschipcraft/fabric_make_bubbles_pop_mod/assets/101755807/1b22bef5-b4ce-4078-ae80-20ffeae7b24f">

### Expected behavior

For bubbles to be visible regardless wether you are under or above water

### Additional context

The issue still applies if I remove my other texture packs

**Comment by Tschipcraft** [comment]
Thanks for the bug report.
However, this is an issue in the base game and applies to all particles rendered behind translucent blocks/water if you play with graphics set to Fast or Fancy ([MC-161917](https://bugs.mojang.com/browse/MC-161917)). Try setting your graphics to Fabulous

**Comment by Bkxz** [comment]
Thanks a lot for the help. Sorry for disturbing you because of my lack of research lol

**Comment by Tschipcraft** [comment]
No problem, issues are always welcome
