### ISSUE TITLE
[Request] Toggle Options

### ISSUE THREAD

**Issue by itsMarkiS** [Tschipcraft/fabric_make_bubbles_pop_mod#4]
### Is your suggested enhancement related to a problem? Please describe.

i really love the mod even if it is just some small details, but the thing is that sometimes i just dont want the bubbles to work with some features, like when im fishing

### Describe the solution you'd like

adding a option to toggle on-off in config files

### Describe alternatives you've considered

disabling it
or adding modmenu config

**Comment by Tschipcraft** [comment]
I sadly can't detect how bubbles particles got spawned into the world, for example via fishing, so a setting like that would just disable overhauled bubble particles in general.
In what scenarios would you like to be able to disable the bubbles and is it just the overhauled motion, the popping itself or the sounds?

**Comment by Answordy** [comment]
Ocean monuments are super laggy with the mod, would be nice if bubbles made by guardians would be ignored, but thats probably not possible, sadly.

**Comment by Tschipcraft** [comment]
No, the only option would be to completely disable bubbles spawned by guardians or to generally lower the bubble lifetime with a settings slider or smth

**Comment by Answordy** [comment]
Well, even those options are better than having 10-20 fps or turning off the mod/all bubble particles. But that is just my opinion.

**Comment by Tschipcraft** [comment]
Damn, I really didn't expect it being that bad for lower end machines...
Will be changed in the future

**Comment by ihnele** [comment]
This is also really bad when you're using a pearl stasis chamber with several pearls floating in soul sand.
