### ISSUE TITLE
Varied Bubble Pop Volume

### ISSUE THREAD

**Issue by NiveStinks** [Tschipcraft/fabric_make_bubbles_pop_mod#8]
### Describe the solution you'd like

It'd be nice if the sound effects for when a bubble pops had varied volume instead of all being at 0.1. Bubbles often generate in large quantities and them all popping at the same volume can be a bit annoying. In fact, maybe even some of them should make no sound at all.

**Comment by Tschipcraft** [comment]
Thank you for the great suggestion, this will be added in a future release
