### ISSUE TITLE
Magma block bubble column appears to pop inside the block rather than on the top

### ISSUE THREAD

**Issue by YoshiRulz** [Tschipcraft/fabric_make_bubbles_pop_mod#9]
### Is your feature request related to a problem? Please describe.

Title. This isn't the fault of the mod, it also happens in vanilla (the bubbles blink out of existence halfway inside the block).

### Describe the feature you'd like

Either adjusting the bubbles' target Y if possible, or collision detection.

### Additional context

Using version 0.2.0 of the mod for Fabric on MC 1.20.4.

**Comment by Tschipcraft** [comment]
Thank you for the great suggestion, now that you mentioned it I'm bothered by it as well. This will be implemented in a future update!

**Comment by Tschipcraft** [comment]
This is the current progress. What do you think @YoshiRulz?

https://github.com/Tschipcraft/make_bubbles_pop/assets/78470530/891d653f-acbf-43e3-9cbe-314985c0436d

**Comment by YoshiRulz** [comment]
Looks great!
